# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('fone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
