# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyneArts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cfp', models.CharField(max_length=11)),
                ('fone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
    ]
