# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 23:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyneArts', '0002_administrador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrador',
            old_name='cfp',
            new_name='cpf',
        ),
    ]
