# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyneArts', '0003_auto_20170621_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=45)),
                ('senha', models.CharField(max_length=16)),
            ],
        ),
    ]
