# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyneArts', '0007_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='id_usuario',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
